---
- name: prepare web
  hosts: web
  become: yes

  tasks:
    - name: Ensure all packages is present
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - default-jdk
        - tomcat9

    - name: ensure tomcat is started
      service:
        name: tomcat9
        state: started

- name: prepare builder
  hosts: builder
  become: yes

  tasks:
    - name: Ensure all packages installed
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - default-jdk
        - maven

    - name: ensuring the repo checkout exists
      git:
        repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
        dest: /tmp/boxfuse-sample-java-war-hello
        update: yes

    - name: ensure if package is built
      shell: mvn package -f /tmp/boxfuse-sample-java-war-hello/

    - name: Synchronize two directories on one remote host.
      synchronize:
        src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
        dest: /var/lib/tomcat9/webapps/hello-1.0.war
      delegate_to: "{{ web }}"